apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: snapshotpolicies.snapitcontroller.controller.io
spec:
  group: snapitcontroller.controller.io
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                pvcName:
                  type: string
                snapshotClassName:
                  type: string
                schedule:
                  type: string
                retention:
                  type: integer
            status:
              type: object
              properties:
                lastSnapshotTime:
                  type: string
                  format: date-time
                lastProcessedRequestID:
                  type: string
                phase:
                  type: string
                message:
                  type: string
      subresources:
        status: {}
  scope: Namespaced
  names:
    plural: snapshotpolicies
    singular: snapshotpolicy
    kind: SnapshotPolicy
    shortNames:
      - snapit
